#!.venv/bin/python

import sys
from bigfiles.server import Server
from bigfiles.client import Client

argumentos = sys.argv[1:]
client = Client()
# client.run(argumentos)
client.upload("arquivos/dinossauro.webp")

